# Generated by Django 5.1.3 on 2026-03-18 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_address_tenant_logo_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='leave_approval_level',
            field=models.CharField(choices=[('SUPERVISOR', 'Hanya Atasan'), ('HR', 'Hanya HR/Admin'), ('BOTH', 'Keduanya (Atasan & HR)')], default='BOTH', max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_admins',
            field=models.IntegerField(default=5, help_text='Batas maksimal jumlah administrator untuk tenant ini (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='overtime_approval_level',
            field=models.CharField(choices=[('SUPERVISOR', 'Hanya Atasan'), ('HR', 'Hanya HR/Admin'), ('BOTH', 'Keduanya (Atasan & HR)')], default='BOTH', max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarif lembur per jam global (0 = gunakan formula)', max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payroll_overtime_divisor',
            field=models.IntegerField(default=173, help_text='Standard pembagi upah lembur (default Indonesia: 173)'),
        ),
    ]
