# Generated by Django 5.1.3 on 2026-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_leave_approval_level_tenant_max_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text="List of enabled modules (e.g. ['payroll', 'attendance'])"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='grace_period_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_employees',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum number of employees allowed for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_type',
            field=models.CharField(choices=[('BASIC', 'Basic (Digital Presence)'), ('PROFESSIONAL', 'Professional (Operational Efficiency)'), ('ENTERPRISE', 'Enterprise (Strategic Human Capital)')], default='ENTERPRISE', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reimbursement_approval_level',
            field=models.CharField(choices=[('SUPERVISOR', 'Hanya Atasan'), ('HR', 'Hanya HR/Admin'), ('BOTH', 'Keduanya (Atasan & HR)')], default='BOTH', max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired (Read-Only)'), ('SUSPENDED', 'Suspended (Blocked)')], default='ACTIVE', max_length=20),
        ),
    ]
