# Generated by Django 6.0.3 on 2026-03-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_enabled_modules_tenant_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='jkk_rate',
            field=models.DecimalField(decimal_places=4, default=0.0024, help_text='Tarif JKK (Jaminan Kecelakaan Kerja) sesuai tingkat risiko (0.24% - 1.74%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=100, help_text='Maximum storage allowed for this tenant in MB'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='storage_used_bytes',
            field=models.PositiveBigIntegerField(default=0, help_text='Current storage usage in bytes'),
        ),
    ]
