# Generated by Django 6.0.3 on 2026-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_jkk_rate_tenant_storage_limit_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme_primary_color',
            field=models.CharField(default='#6366f1', help_text='Primary brand color (hex)', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='theme_secondary_color',
            field=models.CharField(default='#4f46e5', help_text='Secondary brand color (hex)', max_length=10),
        ),
    ]
