# Generated by Django 5.2.12 on 2026-04-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_theme_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='plan_type',
            field=models.CharField(choices=[('ESSENTIAL', 'Essential HR'), ('PROFESSIONAL', 'Professional'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='PROFESSIONAL', max_length=20),
        ),
    ]
