# Generated by Django 5.2.12 on 2026-04-16 22:44

from django.db import migrations


def migrate_plans(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    # Update BASIC to ESSENTIAL
    Tenant.objects.filter(plan_type='BASIC').update(plan_type='ESSENTIAL')
    # Quotas are updated in the model's save() or we can update them here too if needed.
    # For now, we update the plan_type.

def reverse_plans(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    Tenant.objects.filter(plan_type='ESSENTIAL').update(plan_type='BASIC')

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenant_plan_type'),
    ]

    operations = [
        migrations.RunPython(migrate_plans, reverse_plans),
    ]
