# Generated by Django 5.2.12 on 2026-04-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_migrate_plan_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='extra_employees',
            field=models.PositiveIntegerField(default=0, help_text='Additional employee quota purchased via add-ons'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_employees',
            field=models.PositiveIntegerField(default=10, help_text='Base maximum number of employees allowed for this plan'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Tier'), ('ESSENTIAL', 'Essential HR'), ('PROFESSIONAL', 'Professional'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
    ]
