# Generated by Django 5.2.12 on 2026-04-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_extra_employees_alter_tenant_max_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='extra_storage_mb',
            field=models.PositiveIntegerField(default=0, help_text='Additional storage quota purchased via add-ons (MB)'),
        ),
    ]
