# Generated by Django 5.2.12 on 2026-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_extra_storage_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='employee_count',
            field=models.PositiveIntegerField(default=0, help_text='Current number of employees in this tenant'),
        ),
    ]
