# Generated by Django 5.2.12 on 2026-04-18 20:04

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='absence_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Potongan gaji jika alpa (flat per hari)', max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='late_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Potongan tunjangan makan/transport jika terlambat (flat)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.tenant_logo_upload_path),
        ),
    ]
