# Generated by Django 5.2.12 on 2026-04-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_absence_deduction_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_biometric_enabled',
            field=models.BooleanField(default=True, help_text='Allow clock-in without photo if disabled (Emergency Storage Fallback)'),
        ),
    ]
