# Generated by Django 5.2.12 on 2026-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_is_biometric_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='attendance_platform_policy',
            field=models.CharField(choices=[('MOBILE', 'Mobile Only'), ('BOTH', 'Mobile & Web')], default='MOBILE', help_text='Control which platform is allowed for clock-in/out.', max_length=10),
        ),
    ]
