# Generated by Django 5.2.12 on 2026-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_attendance_platform_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_fingerprint_enabled',
            field=models.BooleanField(default=False, help_text='Enable fingerprint integration (physical devices and mobile biometrics)'),
        ),
    ]
