# Generated by Django 5.2.12 on 2026-05-21 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenant_is_fingerprint_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_email', models.EmailField(max_length=254, verbose_name='creator email')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('BILLING', 'Billing & Subscription'), ('BUG', 'System Bug / Error'), ('FEATURE_REQUEST', 'Feature Request'), ('ONBOARDING', 'Onboarding Assistance'), ('OTHER', 'Other Technical Support')], default='OTHER', max_length=20, verbose_name='category')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'global_role__in': ['SUPERADMIN', 'SUPPORT_AGENT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_platform_tickets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_tickets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'platform ticket',
                'verbose_name_plural': 'platform tickets',
            },
        ),
        migrations.CreateModel(
            name='PlatformTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenants.platformticket')),
            ],
            options={
                'verbose_name': 'platform ticket message',
                'verbose_name_plural': 'platform ticket messages',
            },
        ),
    ]
