# Generated by Django 5.2.12 on 2026-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='category',
            field=models.CharField(choices=[('ADMIN', 'System & Billing'), ('OPERATIONAL', 'Employee & Workflow')], default='OPERATIONAL', max_length=15, verbose_name='category'),
        ),
    ]
