# Generated by Django 5.2.12 on 2026-04-17 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_tenant_extra_employees_alter_tenant_max_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('midtrans_order_id', models.CharField(max_length=100, unique=True)),
                ('snap_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('months_added', models.PositiveIntegerField(default=1)),
                ('is_addon', models.BooleanField(default=False, help_text='True if this is an employee quota purchase')),
                ('addon_count', models.PositiveIntegerField(default=0, help_text='Number of employees added if is_addon is True')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
