# Generated by Django 5.2.12 on 2026-04-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='is_storage_addon',
            field=models.BooleanField(default=False, help_text='True if this is a storage quota purchase'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='storage_gb_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of GB added if is_storage_addon is True'),
        ),
    ]
