# Generated by Django 5.2.12 on 2026-04-18 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptioninvoice_is_storage_addon_and_more'),
        ('tenants', '0014_tenant_is_biometric_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaReductionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_gb_reduction', models.PositiveIntegerField(help_text='Amount of GB to reduce from extra storage')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('reason', models.TextField(help_text="Tenant's reason for reduction")),
                ('admin_note', models.TextField(blank=True, help_text="Super Admin's review note")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_reductions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
