# Generated by Django 6.0.3 on 2026-03-19 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_accessrole_options_alter_department_options_and_more'),
        ('reimbursement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'verbose_name': 'reimbursement', 'verbose_name_plural': 'reimbursements'},
        ),
        migrations.AlterModelOptions(
            name='reimbursementcategory',
            options={'verbose_name': 'reimbursement category', 'verbose_name_plural': 'reimbursement categories'},
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='approved amount'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reimbursements/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='reimbursement.reimbursementcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='core.employee', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='finance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='finance status'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='receipt number'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='supervisor_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='supervisor status'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reimbursementcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='reimbursementcategory',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='maximum amount'),
        ),
        migrations.AlterField(
            model_name='reimbursementcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reimbursementcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reimbursementcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
