# Generated by Django 5.2.12 on 2026-04-18 03:25

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_alter_reimbursement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.reimbursement_upload_path, verbose_name='attachment'),
        ),
    ]
