# Generated by Django 5.2.12 on 2026-04-18 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_face_reference_and_more'),
        ('reimbursement', '0003_alter_reimbursement_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstage', verbose_name='current stage'),
        ),
    ]
