# Generated by Django 6.0.3 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_shift_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='liveness_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('FACE', 'Face Match'), ('LIVENESS', 'Face + Liveness')], default='MANUAL', max_length=20),
        ),
    ]
