# Generated by Django 5.2.12 on 2026-04-18 03:25

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancecorrectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='photo_in',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.attendance_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.leave_attachment_upload_path),
        ),
    ]
