# Generated by Django 5.2.12 on 2026-04-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_photo_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='biometric_skipped',
            field=models.BooleanField(default=False, help_text='True if clock-in was performed without photo due to tenant policy'),
        ),
    ]
