# Generated by Django 5.2.12 on 2026-04-22 23:19

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_biometric_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='photo_out',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.attendance_photo_upload_path),
        ),
    ]
