# Generated by Django 5.2.12 on 2026-05-21 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_latitude_out_attendance_longitude_out_and_more'),
        ('core', '0015_employee_biometric_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('FACE', 'Face Match'), ('LIVENESS', 'Face + Liveness'), ('FINGERPRINT', 'Fingerprint Machine'), ('MOBILE_FINGERPRINT', 'Mobile Fingerprint')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='FingerprintDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP Lokal jika menggunakan Local Agent', null=True)),
                ('port', models.IntegerField(default=4370)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_devices', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biometric_pin', models.CharField(help_text='PIN Karyawan pada mesin', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('verification_mode', models.IntegerField(default=1, help_text='1: Finger, 2: Face, 3: Card, 4: Password')),
                ('in_out_state', models.CharField(choices=[('IN', 'Masuk'), ('OUT', 'Keluar'), ('AUTO', 'Deteksi Otomatis')], default='AUTO', max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='attendance.fingerprintdevice')),
            ],
            options={
                'unique_together': {('biometric_pin', 'timestamp')},
            },
        ),
    ]
