# Generated by Django 5.2.12 on 2026-04-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_global_admin_user_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, help_text='Pengguna setuju menerima notifikasi via email'),
        ),
    ]
