# Generated by Django 5.2.12 on 2026-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_receive_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Administrator'), ('ONBOARDING_AGENT', 'Onboarding & Sales'), ('SUPPORT_AGENT', 'Customer Support'), ('BILLING_ADMIN', 'Billing & Finance')], help_text='Menentukan akses pada Portal Admin Utama (SaaS)', max_length=50, null=True),
        ),
    ]
