# Generated by Django 6.0.3 on 2026-03-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_reference',
            field=models.ImageField(blank=True, help_text='Master photo for face recognition', null=True, upload_to='face_references/'),
        ),
    ]
