# Generated by Django 5.1.3 on 2026-03-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accessrole_employee_access_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.employee'),
        ),
        migrations.AddField(
            model_name='golongan',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarif lembur per jam (0 = gunakan formula standar)', max_digits=12),
        ),
    ]
