# Generated by Django 6.0.3 on 2026-03-19 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_supervisor_golongan_overtime_rate'),
        ('tenants', '0006_tenant_jkk_rate_tenant_storage_limit_mb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrole',
            options={'verbose_name': 'access role', 'verbose_name_plural': 'access roles'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterModelOptions(
            name='golongan',
            options={'verbose_name': 'golongan', 'verbose_name_plural': 'golongan'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accessrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='access_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.accessrole', verbose_name='access role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='face_reference',
            field=models.ImageField(blank=True, help_text='Master photo for face recognition', null=True, upload_to='face_references/', verbose_name='face reference'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='golongan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.golongan', verbose_name='golongan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(verbose_name='join date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ktp_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='KTP number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=models.CharField(help_text='Nomor Induk Karyawan', max_length=50, unique=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='npwp_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NPWP number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ptkp_status',
            field=models.CharField(choices=[('TK/0', 'TK/0: Single, No dependents'), ('TK/1', 'TK/1: Single, 1 dependent'), ('TK/2', 'TK/2: Single, 2 dependents'), ('TK/3', 'TK/3: Single, 3 dependents'), ('K/0', 'K/0: Married, No dependents'), ('K/1', 'K/1: Married, 1 dependent'), ('K/2', 'K/2: Married, 2 dependents'), ('K/3', 'K/3: Married, 3 dependents')], default='TK/0', max_length=5, verbose_name='PTKP status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.role', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('PROBATION', 'Probation')], default='PROBATION', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.employee', verbose_name='supervisor'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, help_text='Gaji Pokok', max_digits=12, verbose_name='base salary'),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tunjangan Makan Harian', max_digits=10, verbose_name='meal allowance'),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarif lembur per jam (0 = gunakan formula standar)', max_digits=12, verbose_name='overtime rate'),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tunjangan Transport Harian', max_digits=10, verbose_name='transport allowance'),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. Zapier, ERP Sync', max_length=100, verbose_name='label')),
                ('key_prefix', models.CharField(max_length=8, unique=True)),
                ('key_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('changed_fields', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('radius_meters', models.IntegerField(default=100, help_text='Allow clock-in within this radius', verbose_name='radius in meters')),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=100, verbose_name='timezone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.branch', verbose_name='branch'),
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('SUCCESS', 'Success')], default='INFO', max_length=10, verbose_name='level')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='target user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system notification',
                'verbose_name_plural': 'system notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='workflow name')),
                ('model_type', models.CharField(choices=[('LEAVE', 'Leave Request'), ('OVERTIME', 'Overtime Request'), ('REIMBURSEMENT', 'Reimbursement'), ('TRANSFER', 'Employee Transfer')], max_length=50, verbose_name='model type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workflow config',
                'verbose_name_plural': 'workflow configs',
                'unique_together': {('model_type',)},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='stage name')),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Order of approval (1, 2, 3...)', verbose_name='sequence')),
                ('approver_type', models.CharField(choices=[('SUPERVISOR', 'Direct Supervisor'), ('ROLE', 'Specific Access Role'), ('EMPLOYEE', 'Specific Employee')], default='SUPERVISOR', max_length=20, verbose_name='approver type')),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='approver employee')),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accessrole', verbose_name='approver role')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.workflowconfig', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'workflow stage',
                'verbose_name_plural': 'workflow stages',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned/Revised')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='actor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflowstage', verbose_name='stage')),
            ],
            options={
                'verbose_name': 'workflow action',
                'verbose_name_plural': 'workflow actions',
            },
        ),
    ]
