# Generated by Django 6.0.3 on 2026-03-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_accessrole_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='tenant',
        ),
    ]
