# Generated by Django 6.0.3 on 2026-03-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_apikey_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfig',
            name='model_type',
            field=models.CharField(choices=[('LEAVE', 'Leave Request'), ('OVERTIME', 'Overtime Request'), ('REIMBURSEMENT', 'Reimbursement'), ('TRANSFER', 'Employee Transfer'), ('ATTENDANCE_CORRECTION', 'Attendance Correction')], max_length=50, verbose_name='model type'),
        ),
    ]
