# Generated by Django 6.0.3 on 2026-03-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_workflowconfig_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='home address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ktp_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_docs/ktp/', verbose_name='KTP document scan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='npwp_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_docs/npwp/', verbose_name='NPWP document scan'),
        ),
    ]
