# Generated by Django 6.0.3 on 2026-03-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employee_address_employee_ktp_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='actor'),
        ),
    ]
