# Generated by Django 5.2.12 on 2026-04-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_actor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemNotification',
        ),
    ]
