# Generated by Django 5.2.12 on 2026-04-18 03:25

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_systemnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_reference',
            field=models.ImageField(blank=True, help_text='Master photo for face recognition', null=True, upload_to=core.utils.face_reference_upload_path, verbose_name='face reference'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ktp_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.ktp_upload_path, verbose_name='KTP document scan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='npwp_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.npwp_upload_path, verbose_name='NPWP document scan'),
        ),
    ]
