# Generated by Django 5.2.12 on 2026-05-10 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_face_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Golongan',
            new_name='Grade',
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='golongan',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.grade', verbose_name='grade'),
        ),
    ]
