# Generated by Django 5.2.12 on 2026-05-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_golongan_grade_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('PROBATION', 'Probation'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned'), ('SUSPENDED', 'Suspended'), ('INTERN', 'Internship'), ('FREELANCE', 'Freelance')], default='PROBATION', max_length=20, verbose_name='status'),
        ),
    ]
