# Generated by Django 5.2.12 on 2026-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric_pin',
            field=models.CharField(blank=True, help_text='PIN/Enrollment ID of employee on fingerprint machine', max_length=50, null=True, unique=True, verbose_name='biometric PIN'),
        ),
    ]
